# Generated by Django 4.0 on 2022-11-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_company_alter_hotel_description_alter_hotel_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
