# Generated by Django 4.0 on 2022-11-22 12:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_product_company_delete_company_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Контактный номер')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('comment', models.TextField(max_length=500, null=True, verbose_name='Комментарий')),
            ],
        ),
    ]
