# Generated by Django 4.0 on 2022-11-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='manager',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='tours.manager', verbose_name='ФИО управляющего'),
            preserve_default=False,
        ),
    ]
