# Generated by Django 4.1.3 on 2022-11-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_hotel_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Управляющий', 'verbose_name_plural': 'Управляющие'},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название отеля'),
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(choices=[('0', 'Без питания'), ('1', 'С завтраком'), ('2', '3-х разовое')], max_length=200, verbose_name='Вид питания')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
