# Generated by Django 4.1.3 on 2022-11-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_hotel_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='date_of_stay',
            field=models.DateField(default=-2012, verbose_name='Дата заезда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='description',
            field=models.TextField(default=123, max_length=500, verbose_name='Описание тура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='numbers_day',
            field=models.IntegerField(default=123, verbose_name='Количество дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='price',
            field=models.IntegerField(default=123, verbose_name='Стоимость тура'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('option', models.CharField(choices=[('Физическое лицо', 'Физическое лицо'), ('Юридическое лицо', 'Юридическое лицо')], max_length=100, verbose_name='Вид клиента')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.manager', verbose_name='Контактное лицо')),
            ],
        ),
    ]
