# Generated by Django 4.1.3 on 2022-11-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tours_date_of_stay_tours_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='date_of_stay',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заезда'),
        ),
    ]
